# --- 默认配置 ---

# --- pymarl 选项 ---
runner: "episode" # 运行一个环境的一个回合
mac: "basic_mac" # 基础控制器
env: "sc2" # 环境名称
#env: "hok"
env_args: {} # 环境参数
batch_size_run: 1 # 并行运行的环境数量
test_nepisode: 20 # 测试回合数
test_interval: 2000 # 每隔{}时间步进行测试
test_greedy: True # 使用贪婪评估(如果为False，将设置epsilon最小值为0)
log_interval: 2000 # 每隔{}时间步记录统计摘要
runner_log_interval: 2000 # 每隔{}时间步记录运行器统计(非测试统计)
learner_log_interval: 2000 # 每隔{}时间步记录训练统计
t_max: 10000 # 运行达到此时间步数后停止
use_cuda: True # 默认使用GPU，除非不可用
buffer_cpu_only: True # 如果为true，不会将所有重放缓冲区保存在显存中

# --- 日志选项 ---
use_tensorboard: False # 将结果记录到tensorboard
save_model: True # 将模型保存到磁盘
save_model_interval: 2000 # 每隔此时间步数保存模型
checkpoint_path: "" # 从此路径加载检查点

checkpoint_path: "" # qplex

evaluate: False # 评估模型test_nepisode回合数后退出(不训练)
load_step: 0 # 加载在此时间步数训练的模型(0表示选择最大可能值)
save_replay: False # 保存从checkpoint_path加载的模型的重放
local_results_path: "results" # 本地结果路径

# --- 强化学习超参数 ---
gamma: 0.99
batch_size: 32 # 训练的回合数
buffer_size: 32 # 重放缓冲区大小
lr: 0.0005 # 智能体学习率
critic_lr: 0.0005 # 评判器学习率
optim_alpha: 0.99 # RMSProp alpha参数
optim_eps: 0.00001 # RMSProp epsilon参数
grad_norm_clip: 10 # 减少梯度幅度，当L2范数超过此值时
# hc
add_value_last_step: True

# --- 智能体参数 ---
agent: "rnn" # 默认RNN智能体
rnn_hidden_dim: 64 # 默认RNN智能体的隐藏状态大小
obs_agent_id: True # 在观察中包含智能体的独热编码ID
obs_last_action: True # 在观察中包含智能体的最后一个动作(独热编码)

# --- 实验运行参数 ---
repeat_id: 1
label: "default_label"

run: "default"
